name: herbcalm
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  google_fonts: ^6.1.0
  firebase_core: ^2.24.2
  persistent_bottom_nav_bar: ^5.0.2
  sticky_headers: ^0.3.0+2
  animated_splash_screen: ^1.3.0
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  auto_size_text: ^3.0.0
  flutter_chat_ui: ^1.6.10
  flutter_chat_types: ^3.6.2
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  open_filex: ^4.3.4
  http: ^1.1.2
  path_provider: ^2.1.2
  bubble: ^1.2.1
  firebase_database: ^10.4.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/logo-launcher-white.png"
  adaptive_icon_background: '#128D61'
 
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter



flutter: 
  uses-material-design: true
  assets:

    - assets/images/logo/logo-launcher-white.png
    - assets/svg/home/obatherbal.svg
    - assets/svg/home/konsultasi.svg
    - assets/svg/home/meditasi.svg
    - assets/svg/home/resepobat.svg
    - assets/svg/chat/addChat.svg
    - assets/svg/forum/addForum.svg

