name: herbcalm
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  google_fonts: ^6.1.0
  firebase_core: ^2.24.2
  persistent_bottom_nav_bar: ^5.0.2
  sticky_headers: ^0.3.0+2
  animated_splash_screen: ^1.3.0
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
 
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/screenshoot/1.jpg
    - assets/images/screenshoot/2.jpg
    - assets/images/screenshoot/3.jpg
    - assets/images/logo/logo-herbcalm-bg.jpeg
    - assets/images/logo/logo.png
    - assets/images/dokter/dr1.png
    - assets/images/dokter/dr2.png
    - assets/images/profile.jpeg
    - assets/images/artikelImage/image1.png
    - assets/images/artikelImage/image2.png
    - assets/images/artikelImage/carousel.png
    - assets/images/obatJamu/lancarhaid.png
    - assets/svg/home/obatherbal.svg
    - assets/svg/home/konsultasi.svg
    - assets/svg/home/meditasi.svg
    - assets/svg/home/resepobat.svg
    - assets/svg/chat/addChat.svg
    - assets/svg/forum/addForum.svg

